### ISSUE TITLE
[PERMANENT] Performance profiling

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/CounterfactualExplanations.jl#144]
I've noted that independent on the input dimension, performance seems to suffer as the number of observations in the dataset increases. This is quite odd, because counterfactual search happens at the individual level. Using [profiling](https://www.julia-vscode.org/docs/dev/userguide/profiler/), we should try to identify and remove bottlenecks.

**Example**:

```julia
# Counteractual data and model:
counterfactual_data = load_linearly_separable(100)
counterfactual_data_large = load_linearly_separable(100000)
M = fit_model(counterfactual_data, :Linear)
target = 2
factual = 1
chosen = rand(findall(predict_label(M, counterfactual_data) .== factual))
x = select_factual(counterfactual_data, chosen)

# Search:
generator = GenericGenerator()
ce = generate_counterfactual(x, target, counterfactual_data, M, generator)
```

```julia
julia> @time generate_counterfactual(x, target, counterfactual_data, M, generator)
  0.007391 seconds (17.93 k allocations: 1.434 MiB)
```

```julia
julia> @time generate_counterfactual(x, target, counterfactual_data_large, M, generator)
  0.398706 seconds (27.79 k allocations: 176.259 MiB, 21.01% gc time)
```

**Task list**

- [x] #436
- [x] #145

**Comment by pat-alt** [comment]
Think that part of the problem might be that the `CounterfactualExplanation` composite type has turned into a bit of a monster. Even at instantiation we can see the difference:

```julia
julia> @time CounterfactualExplanation(x=x, target=target, data=counterfactual_data, M=M, generator=generator)
  0.000762 seconds (1.28 k allocations: 227.156 KiB)
julia> @time CounterfactualExplanation(x=x, target=target, data=counterfactual_data_large, M=M, generator=generator)
  0.057782 seconds (9.93 k allocations: 56.627 MiB)
```

**Comment by pat-alt** [comment]
cc @izagorac

**Comment by izagorac** [comment]
This is indeed exactly the finding that I had as well @pat-alt

**Comment by pat-alt** [comment]
@izagorac #439 is now merged. I haven't tested this specifically for FeatureTweak, but for gradient-based generators there is now little to no dependence on the number of samples in the dataset.
