### ISSUE TITLE
[Generator] Add the PROBE generator

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#162]
Implement the approach described in [this paper by Pawelczyk et al.](https://arxiv.org/abs/2203.06768)

- [x] Make a new R Hinge Loss function in objectives/loss_functions.jl
- [x] Make loss function that combines R and MSE  in objectives/loss_functions.jl
- [x] Implement Theorem 1 to check for convergence and use in the loss
- [x] Take care of convergence criterium   
- [x] Add to progress notebook

**Comment by VincentPikand** [comment]
closed by #104
