### ISSUE TITLE
[Benchmarks] Add the CIFAR-10 dataset

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#167]
Add the CIFAR-10 dataset into the package.

To do: 
- [x] add functionality to the `src\data\vision.jl` file (loader functions)
- [x] export implemented functions in the `src\data\Data.jl` file
- [x] test implemented functions
- [x] update dataset notebook `dev\artifacts\vision.qmd`
- [x] add function `load_cifar_10` to the `src\models\pretrained.jl`, so users can deserialize pre-trained models

**Comment by kmariuszk** [comment]
We missed updating the `pretrained.jl` file while we were initially implementing this. To fix that I opened another PR #205.

**Comment by A-Salmon** [comment]
This is done now right?

**Comment by VincentPikand** [comment]
closed by #190
