### ISSUE TITLE
[Benchmarks] Add the Statlog German Credit dataset

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#168]
Add the Statlog German Credit dataset into the package.

To do:
- [x] add functionality to the `src\data\tabular.jl` file (loader functions)
- [x] export implemented functions in the `src\data\Data.jl` file
- [x] test implemented functions
- [x] update dataset notebook `dev\artifacts\tabular.qmd`
- [x] mention adding Statlog German Credit dateset in the `students_documentation\summary.qmd`
- [x] mention adding Statlog German Credit dateset in the `students_documentation\README.md`
- [x] add examples that demonstrate the usage of the Statlog German Credit dataset in the `students_documentation\summary.qmd`
- [x] include documentation about Statlog German Credit in the `docs/src/tutorials/data_catalogue/` section
- [x] add Statlog German Credit dataset to https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/releases/tag/artifacts-1.8

**Comment by VincentPikand** [comment]
closed by #199
