### ISSUE TITLE
Investigate `ONNX.jl` to handle R models

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#172]
Instead of relying on `RCall` to explain models trained in R, investigate whether it's possible to use [ONNX.jl](https://github.com/FluxML/ONNX.jl) to transform models into `Flux` models and then proceed as usual.

**Comment by kmariuszk** [comment]
It turns out it was impossible to use ONNX (since it's being restructured) to handle R models but instead, we used the RCall package to achieve similar results. The functionality has already been merged #234.
