### ISSUE TITLE
Final summary

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#177]
Once the implemention part of the project has been finished, create an interactive notebook or blog post that summarizes all of our work to create a concise summary of what we've done and to share our progress with the wider Julia community.

Also,
- [ ] close #236

**Comment by Roh-codeur** [comment]
Hi mate, amazing package! 

If I may, I would like to vote for this as well. I think the plotting is great, but I couldn’t find a way to get the results in a tabular form showing counterfactuals.
