### ISSUE TITLE
[Interface to MLJ] Implement a single class to handle all MLJ models

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#178]
If the investigation conducted as part of issue #175 is successful, implement a single class to handle all MLJ models.

**Comment by VincentPikand** [comment]
Dropped as part of the `CSE2000 Software Project` after a discussion with @pat-alt prioritizing tasks.

**Comment by pat-alt** [comment]
closing because we still have #69
