### ISSUE TITLE
[Penalty strengths] Determine the optimal penalty strengths

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#179]
Currently, the choices for the default values of parameters governing the penalty strength is based on the literature and related software implementations. We would like to make more principled choices based on benchmarking.

Perform benchmarking experiments on 1 synthetic and 1 real-world dataset from the package to determine the optimal penalty strength for the generators.

**Comment by VincentPikand** [comment]
closed by #251
