### ISSUE TITLE
[Penalty strengths] Investigate ML models for penalty strength tuning

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#181]
Currently, the choices for the default values of parameters governing the penalty strength is based on the literature and related software implementations. We would like to tune these penalty strength choices in the future with the help of machine learning.

For this, investigate the ways in which penalty strengths can be tuned using ML techniques.

**Comment by VincentPikand** [comment]
Dropped as part of the `CSE2000 Software Project` after a discussion with our client prioritizing tasks.

**Comment by pat-alt** [comment]
Close in favour of #180
