### ISSUE TITLE
[Penalty strengths] Interactive notebook for penalty strength tuning

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#182]
Currently, the choices for the default values of parameters governing the penalty strength is based on the literature and related software implementations. We would like to also allow users themselves to make their own choices for the penalty strengths.

Create an interactive `Pluto.jl` notebook that allows the user to explore different penalty strength choices themselves.

**Comment by VincentPikand** [comment]
closed by #251
