### ISSUE TITLE
[Penalty strengths] Implement penalty strength tuning through ML

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#183]
Currently, the choices for the default values of parameters governing the penalty strength is based on the literature and related software implementations. We would like to tune these penalty strength choices in the future with the help of machine learning.

If we find that doing this is feasible as part of issue #181, implement the corresponding models.

**Comment by VincentPikand** [comment]
Dropped as part of the `CSE2000 Software Project` after a discussion with our client prioritizing tasks.

**Comment by pat-alt** [comment]
Close in favour of #180
