### ISSUE TITLE
Improve visualization

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#184]
Multivariate input data is currently visualized using PCA. The quality of these visualisations decreases proportionately to the increase of the dimensionality of the input data. Investigate using compression techniques such as UMAP to improve this.

**Comment by VincentPikand** [comment]
https://pair-code.github.io/understanding-umap/

- 2. Cluster sizes in a UMAP plot mean nothing
- 3. Distances between clusters might not mean anything
- decision boundary in UMAP? doesn't really make sense
- UMAP is a "explanation" in and of itself, a counterfactual path would probably be obvious and kind of meaningless (moving from one cluster to another).
