### ISSUE TITLE
Display parameters in docs

### ISSUE THREAD

**Issue by laurikskl** [JuliaTrustworthyAI/CounterfactualExplanations.jl#188]
The tutorials in the documentation make use of pre-defined variables in the quarto notebook, for example:

ce = generate_counterfactual(x, target, counterfactual_data, M, generator; num_counterfactuals=5)
plot(ce)

Following the tutorial is sometimes a bit tricky since you cannot tell what kind of parameters were used.

The variables should be made displayed in the documentation.

**Comment by VincentPikand** [comment]
closed by #249
