### ISSUE TITLE
Break up and sort out imports/exports in `counterfactuals` folder

### ISSUE THREAD

**Issue by laurikskl** [JuliaTrustworthyAI/CounterfactualExplanations.jl#189]
Separate the 700 line long functions.jl into categories, like threshold functions, mapping functions etc. This greatly improves cohesion.

Tasks:

- [x] Create a separate file for threshold functions.
- [x] Create a separate file for mapping functions.
- [x] Create a separate file for latent space model helpers.
- [x] Make sure that the functions remain perfectly integrated with all models and generators in their new files. Create new tests if necessary.
- [x] Rename `counterfactuals/functions.jl`.
- [x] Document all the changes made so that the client can seamlessly transition to the new package structure.

**Comment by VincentPikand** [comment]
closed by #221
