### ISSUE TITLE
Add CIFAR-10 to the summary notebook

### ISSUE THREAD

**Issue by kmariuszk** [JuliaTrustworthyAI/CounterfactualExplanations.jl#194]
Mention adding CIFAR-10 dataset in the summary notebook `.\students_documentation\summary.qmd`.

To do:

- [x] mention adding CIFAR-10 dateset in the `students_documentation\summary.qmd`
- [x] mention adding CIFAR-10 dateset in the `students_documentation\README.md`
- [x] add examples that demonstrate the usage of the CIFAR-10 dataset in the `students_documentation\summary.qmd`
- [x] include documentation about CIFAR-10 in the `dev/tutorials/data_catalogue/` section

**Comment by VincentPikand** [comment]
closed by #190
