### ISSUE TITLE
Pkg Extensions: EvoTrees, MLJDecisionTreeInterface, NearestNeighborModels, LaplaceRedux

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/CounterfactualExplanations.jl#301]

**Comment by RaunoArike** [comment]
Once the Data folder has been moved out to TaijaData, it will become possible to also use an extension for MLJBase. Noting this down here as a future TODO.

**Comment by kmariuszk** [comment]
@RaunoArike Data folder has been just migrated to TaijaData
