### ISSUE TITLE
Pytorch is acting up

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/CounterfactualExplanations.jl#326]
Test keep failing for pytorch models. Let's just move this out entirely into a TaijaInteroperability.jl package.

cc @kmariuszk @VincentPikand @RaunoArike could one of you pick this up? Let's discuss tomorrow

**Comment by RaunoArike** [comment]
Solved by moving the PythonCall and RCall functionality to `TaijaInteroperability.jl`.
