### ISSUE TITLE
Investigate the workflow of CLUE, Wachter and ClaPROAR

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#333]
Create a diagram detailing the process of creating a counterfactual with the CLUE, Wachter and ClaPROAR generators

**Comment by RaunoArike** [comment]
![Image](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/assets/63519956/61c37247-7129-4c6d-95fe-b9862c2c5d9b)

**Comment by RaunoArike** [comment]
### CLUE:

![Image](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/assets/63519956/139fafc3-de30-4589-9d61-74f34e7efcf4)

**Comment by RaunoArike** [comment]
### ClaPROAR:



![Image](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/assets/63519956/88da81e8-d4e5-474c-be2f-861ab5a2dc7d)

**Comment by pat-alt** [comment]
@RaunoArike all these diagrams you created would be nice to add to the docs. What did you use to produce them?

**Comment by RaunoArike** [comment]
I used Figma, you can view and edit them using this link: https://www.figma.com/file/DeWQatn9oou1RQH3y0mO7K/CounterfactualExplanations.jl-diagrams?type=design&node-id=0%3A1&mode=design&t=tM08lDrzCWDDSRw5-1. Feel free to use them for the docs!
