### ISSUE TITLE
Asserts are working unexpectedly for Feature Tweak

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#353]
It seems that the error handling implemented for Feature Tweak is not working properly at the moment:

- when generating a Feature Tweak counterfactual with a model that isn't a TreeModel, a plot of the counterfactual is nevertheless generated

**Comment by pat-alt** [comment]
Asserts have been removed in favor of an `incompatible` method (#450) that can be run outside of the generator function scope. This way, the counterfactual search is not even initiated in case the generator is incompatible with the model, for example.
