### ISSUE TITLE
Growing Spheres is not working for `EvoTrees`

### ISSUE THREAD

**Issue by RaunoArike** [JuliaTrustworthyAI/CounterfactualExplanations.jl#384]
When trying to generate a counterfactual for an `EvoTreeModel` using the Growing Spheres generator which should be compatible with all models, I got the following error inside the `growing_spheres_generation()` method: `ArgumentError: invalid index: nothing of type Nothing`. This issue should be resolved and `EvoTreeModel` should be added to the set of models tested with the Growing Spheres generator to avoid such bugs in the future.

**Comment by pat-alt** [comment]
`EvoTrees` has been temporarily removed in favor of `NeuroTrees`. GrowingSpheres implementation is broken anyway (see #396
