### ISSUE TITLE
Field names of `CounterfactualExplanation` are not obvious enough

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/CounterfactualExplanations.jl#488]
In particular, `ce.x` (factual) and `ce.x′` (counterfactual). Should change the field names to something more obvious and add aliases for old names.

cc @abuszydlik

**Comment by abuszydlik** [comment]
Adding to this `x′` (x-prime) can be easily confused with `x'` (x-apostrophe) and the latter corresponds to the Julia operation of conjugate transposition, which may lead to code issues that are very difficult to debug.
